# Generated by Django 4.2 on 2024-06-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spa_comments_app", "0004_rename_body_comment_text_comment_parent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="username",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
