# Generated by Django 4.2 on 2024-07-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spa_comments_app", "0005_comment_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="tags",
            field=models.TextField(blank=True),
        ),
    ]
