# Generated by Django 4.2 on 2024-07-01 19:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("spa_comments_app", "0006_comment_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="tags",
        ),
    ]
