# Generated by Django 4.2 on 2024-07-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spa_comments_app", "0009_comment_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentlimit",
            name="limit",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
