# Generated by Django 4.2 on 2024-07-04 14:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("spa_comments_app", "0010_alter_commentlimit_limit"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CommentLimit",
        ),
    ]
