# Generated by Django 4.2 on 2024-07-01 07:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="username",
            field=models.CharField(
                default=None,
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[\\w]*$",
                        "This field can contain only numbers, letters, and underscores.",
                    )
                ],
            ),
            preserve_default=False,
        ),
    ]
