# Generated by Django 4.2 on 2024-07-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management_app", "0002_alter_userdata_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
    ]
